### ISSUE TITLE
On Maintenance Page - Current Year an Current Month Should be Selected By Default in Drop Downs

### ISSUE THREAD

**Issue by sandeepsajiru** [sandeepsajiru/flatroll#10]
Currently status grid works fine but we don't get a clue which month/year combination it is showing for.

**Comment by aditya128** [comment]
bug has been fixed and i have pushed the updated maintenance page just now.. verify and  close the issue sir..

**Comment by sandeepsajiru** [comment]
Changes have been deployed to Server, Ready for verification and Closure.

**Comment by chandrasekhar-kv** [comment]
fixed
