### ISSUE TITLE
On Maintenance Page - Grid Should update on changing the Year As well

### ISSUE THREAD

**Issue by sandeepsajiru** [sandeepsajiru/flatroll#11]

**Comment by aditya128** [comment]
bug fixed .. i have pushed just now.. verify and close the issue sir..

**Comment by sandeepsajiru** [comment]
Changes deployed to Server.  Verified them to be working.  Assigning to chandrasekhar-kv for Closure.

**Comment by chandrasekhar-kv** [comment]
done
