### ISSUE TITLE
KV Phase II Link on Maintenane Page still takes to Google Search Results - Needs Fixing

### ISSUE THREAD

**Issue by sandeepsajiru** [sandeepsajiru/flatroll#12]
http://site/maintenance

**Comment by aditya128** [comment]
bug has been fixed and updated maintenance is pushed to git hub.. verify and close the issue sir..

**Comment by sandeepsajiru** [comment]
Deployed to server... Assigning to chandrasekhar-kv  for Verification and Closure.

**Comment by chandrasekhar-kv** [comment]
now o k
