### ISSUE TITLE
what will be displayed under monthly status in dashboard?

### ISSUE THREAD

**Issue by chandrasekhar-kv** [sandeepsajiru/flatroll#13]

**Comment by sandeepsajiru** [comment]
Based on year selected in drop-down we should be showing 
JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC

Assigning to Aditya for fixing... 

Adi - in case it requires any changes @ backend;  Please lot another issue with requirements and assign that to (Nikhil/Rahul) accordingly.

**Comment by aditya128** [comment]
issue resolved .. syncing of changes is required..

**Comment by chandrasekhar-kv** [comment]
ok
