### ISSUE TITLE
property tax number

### ISSUE THREAD

**Issue by chandrasekhar-kv** [sandeepsajiru/flatroll#2]
include property tax no after sale deed regn no

**Comment by sandeepsajiru** [comment]
Hope that expectation was to show data in order SALE DEED DATE, REG NUMBER, PROPERTY TAX NUMBER.

Please see attached screenshot containing the fix results.  Fix has been deployed to production.

![issue 2-fix](https://cloud.githubusercontent.com/assets/8422892/11376096/cfe83caa-9304-11e5-9d5a-190c9bdac5c7.PNG)
