### ISSUE TITLE
electricity customer service number 

### ISSUE THREAD

**Issue by chandrasekhar-kv** [sandeepsajiru/flatroll#3]
to come after property tax no

**Comment by chandrasekhar-kv** [comment]
hi
changes not reflected please
rcs

On Wed, Dec 23, 2015 at 8:57 PM, vjnikhil1 notifications@github.com wrote:

> Closed #3 https://github.com/sandeepsajiru/flatroll/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sandeepsajiru/flatroll/issues/3#event-499520397.

## 

R.Chandrasekhar
Flat  C 50 Block 7 Kendriya Vihar Phase II   Gachibowli
Hyderabad 500 032
Ph: 040-2300 4750

**Comment by aditya128** [comment]
electric city tax number is after property tax number .. once re check it..

**Comment by sandeepsajiru** [comment]
Issue fixed : Please verify and close.

**Comment by chandrasekhar-kv** [comment]
elec con number now ok
