### ISSUE TITLE
Cancellation of EDIT form clears up all the fields in the UI

### ISSUE THREAD

**Issue by sandeepsajiru** [sandeepsajiru/flatroll#6]
Follow these steps:
1.  Open Site - Dashboard Page
2.  Click any flat entry e.g. B-01
3.  Click 'Edit' link on Tenant Details - A popup comes up allowing us the edit details.
4. Cancel this popup.
## RESULT

Cancellation causes all the details - OWNER DETAILS, FLAT DETAILS, TENANT DETAILS to become empty (cleared off).
## EXPECTED

Cancellation of the popup shouldn't clear the values.

**Comment by aditya128** [comment]
Bug is fixed..
