### ISSUE TITLE
under receipts and under payment type edit option to change head of acc like open car parking to car park maintenance and others heads

### ISSUE THREAD

**Issue by chandrasekhar-kv** [sandeepsajiru/flatroll#7]

**Comment by sandeepsajiru** [comment]
Bug is that /receipts page should have in Payment Type.. Every item should have Maintenace added in the end.

e.g. Birthday Event Maintenance
Commercial Event Maintenance.

Is the Understanding Correct?

**Comment by chandrasekhar-kv** [comment]
but how will monthly maintenance charge be shown

**Comment by sandeepsajiru** [comment]
Will "Monthly Maintenance" be appropriate?

Current Heads shown are:
Maintenance
Community Hall Booking
Car Parking
Commercial Event
Birthday Event
Water Charges
Cable Opertors
Internet Operators
Misc Vendors

We need the right terms they should be changed to.

**Comment by chandrasekhar-kv** [comment]
hi
For i t purposes the word maintenance need to be added because these can be
shown as allowable income
The heads can be as under

Monthly maintenance
Hall maintenance
Parking maintenance
Internet cable maintenance
Events rent
Water tankers
Misc vendors

On Saturday, January 2, 2016, sandeepsajiru notifications@github.com
wrote:

> Will "Monthly Maintenance" be appropriate?
> 
> Current Heads shown are:
> Maintenance
> Community Hall Booking
> Car Parking
> Commercial Event
> Birthday Event
> Water Charges
> Cable Opertors
> Internet Operators
> Misc Vendors
> 
> We need the right terms they should be changed to.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sandeepsajiru/flatroll/issues/7#issuecomment-168354644
> .

## 

R.Chandrasekhar
Flat  C 50 Block 7 Kendriya Vihar Phase II   Gachibowli
Hyderabad 500 032
Ph: 040-2300 4750

**Comment by aditya128** [comment]
payment type heads have been updated.. verify and close the issue..

**Comment by chandrasekhar-kv** [comment]
fixed
